/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.gradle.archetype

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.gradle.archetype.greeting' plugin.
 */
class GradleArchetypePluginPluginTest {
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("com.gradle.archetype.cleanArchetype")

        // Verify the result
        assertNotNull(project.tasks.findByName("cleanArchetype"))
    }
}
